### ISSUE TITLE
MMiniDumpWriteDump 值为0，这个是什么原因呐？

### ISSUE THREAD

**Issue by czz1233** [seventeenman/CallBackDump#1]

**Comment by seventeenman** [comment]
请检查是否以管理员权限启动

**Comment by czz1233** [comment]
> 请检查是否以管理员权限启动

我vs调试也需要管理员吗

**Comment by seventeenman** [comment]
> > 请检查是否以管理员权限启动
> 
> 我vs调试也需要管理员吗

是的，右键vs以管理员权限启动，但我猜你会遇到找不到符号表表的问题，这种情况也可以尝试将项目内调用的底层api替换。
但我觉得更好的debug方案是用GetLastError()，你遇到了什么问题需要debug么
