### ISSUE TITLE
vs2019 编译 执行会卡住，不动生成不了

### ISSUE THREAD

**Issue by komomon** [seventeenman/CallBackDump#2]

**Comment by seventeenman** [comment]
ctrl+b可以正常生成exe文件么

**Comment by komomon** [comment]
> ctrl+b可以正常生成exe文件么

是的，可以，编译后执行，整个虚拟机无响应了

**Comment by seventeenman** [comment]
> > ctrl+b可以正常生成exe文件么
> 
> 是的，可以，编译后执行，整个虚拟机无响应了

可以说一下是什么windows版本么，编译后通过管理员cmd执行是否有效呢，或者可以尝试重启一下。如果仍然不可以的话，你可以留个邮箱给我一下
