### ISSUE TITLE
VS2019编译成功，但是运行无反应

### ISSUE THREAD

**Issue by UIWP0** [seventeenman/CallBackDump#3]
VS2019编译属性
![image](https://user-images.githubusercontent.com/32759429/192945314-c3ca7d6c-cd23-43a6-92a2-0f91561db757.png)
![image](https://user-images.githubusercontent.com/32759429/192945420-86c1f1df-84a0-4557-bf5c-7b27d0fea4d3.png)
编译64位
![image](https://user-images.githubusercontent.com/32759429/192945653-408059a9-a6aa-41b5-a726-2aae85e83eb9.png)

运行没有反应
![Uploading image.png…]()
请问是编译时候缺少了什么配置吗

**Comment by seventeenman** [comment]
你好，试试管理员权限运行

**Comment by UIWP0** [comment]
管理员也不行
win10关闭杀软运行
![image](https://user-images.githubusercontent.com/32759429/192952333-fc9c225b-a2df-43fc-afc3-294818e4bfac.png)
win7
![image](https://user-images.githubusercontent.com/32759429/192952442-0f763dcc-9960-451e-8353-1e8248f7d490.png)
编译的时候要导入什么依赖吗？

**Comment by seventeenman** [comment]
依赖项目里面都导入了，C:\Users\Public\Downloads\这个路径下没有东西么

**Comment by UIWP0** [comment]
> 依赖项目里面都导入了，C:\Users\Public\Downloads\这个路径下没有东西么

管理员权限下WIN7生成了log文件，但普通权限不能生成
![image](https://user-images.githubusercontent.com/32759429/192954381-0d9c433f-cf09-4d37-a166-cf26ef062de5.png)
但是WIN10 在管理员权限下仍然没有log文件
![image](https://user-images.githubusercontent.com/32759429/192954806-5c227533-5231-46dc-89ee-2447378d2896.png)

**Comment by seventeenman** [comment]
重新启动一下win10试试看，并且确保生成的是MT。或者你在代码里面输出一下，看看哪里走不进去

**Comment by UIWP0** [comment]
在无杀软的WIN10下测试，给与管理员权限能够产生log文件，在本机存在
![image](https://user-images.githubusercontent.com/32759429/192955938-212fbd62-1b11-460c-a44b-ae97afa822d5.png)
情况下，不能产生log文件，考虑是因为杀软的原因。感谢师傅

**Comment by seventeenman** [comment]
国外一些对lsass保护会拿不了句柄，前几天测的另外一份代码弄错了，我以为是这个dump出来的。昨晚再次测试发现后已更新readme，删除了卡巴斯基，但defender和核晶是没什么问题的。我没有nod32环境，从你的描述来看nod32也是拿不到句柄，感谢你的测试。

**Comment by UIWP0** [comment]
了解，谢谢师傅

**Comment by UIWP0** [comment]
新的问题是这个xor.exe 编译
![image](https://user-images.githubusercontent.com/32759429/192957966-b8338459-3829-4501-a380-d9ae998508ed.png)
![image](https://user-images.githubusercontent.com/32759429/192957990-29372aa4-e55c-4d6a-b5ae-402e2e5aea05.png)
编译报错
![image](https://user-images.githubusercontent.com/32759429/192958021-60a37fc3-0220-4051-b4b3-50b620efd3f9.png)

**Comment by UIWP0** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	dumpXor	D:\CallBackDump-main\CallBackDump-main\dumpXor\dumpXor\main.cpp	22	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C4996	'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.	dumpXor	D:\CallBackDump-main\CallBackDump-main\dumpXor\dumpXor\main.cpp	23	

严重性	代码	说明	项目	文件	行	禁止显示状态
警告	C4101	“tBuffer”: 未引用的局部变量	dumpXor	D:\CallBackDump-main\CallBackDump-main\dumpXor\dumpXor\main.cpp	10

**Comment by seventeenman** [comment]
我会将我编译好的版本通过你的邮箱发送给你，应该是没有关闭vs的安全检测

**Comment by UIWP0** [comment]
感谢师傅 <;

**Comment by UIWP0** [comment]
![img_v2_fbe30956-437f-4bec-b34a-ec4bab56219g](https://user-images.githubusercontent.com/32759429/192962787-2ca54c59-8689-40b5-8d55-72da63d4d522.jpg)
s生成的bin文件被df杀了

**Comment by seventeenman** [comment]
这一部分可以在没有杀软的机器上运行呀，包括后续的mimikatz也是的，这个任务就只是免杀dump lsass进程

**Comment by UIWP0** [comment]
> 这一部分可以在没有杀软的机器上运行呀，包括后续的mimikatz也是的，这个任务就只是免杀dump lsass进程

懂了
