### ISSUE TITLE
生成的 CallbackDump.exe 执行后没有生成 log 文件呢，电脑管家和火绒不拦截，但是360会拦截

### ISSUE THREAD

**Issue by rtfghd** [seventeenman/CallBackDump#4]
### 环境：VS2022，windows10/11

![image](https://user-images.githubusercontent.com/19860485/192972442-35181781-8722-4880-b506-69c7d7ff3dd8.png)

![image](https://user-images.githubusercontent.com/19860485/192971930-56f968bf-2e1b-4aab-acff-631130078337.png)

**Comment by seventeenman** [comment]
看看别的issue，我累了
